import Modal from "@/components/Modal";
import "./globals.scss";
import { Inter } from "next/font/google";
import Providers from "./providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Welcome to listicle App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <Modal />
          <main className="main">{children}</main>
        </Providers>
      </body>
    </html>
  );
}
